{{- $i := range .Values.replicas -}}
apiVersion: v1
kind: Pod
metadata:
  name: iperf-server
  labels:
    app: iperf-{{ $i }}
spec:
  containers:
    - name: iperf-server-{{ $i }}
      image: networkstatic/iperf3
      args: ["-s"]
      ports:
        - containerPort: 5201
      resources:
        requests:
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "128Mi"
          cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: iperf-service-{{ $i }}
  labels:
    app: iperf-{{ $i }}
spec:
  ports:
    - port: 5201
      targetPort: 5201
  selector:
    app: iperf-{{ $i }}
  type: ClusterIP
{{- end -}}